"""Add ingestion and policy models

Revision ID: 04c690da4e15
Revises: 07ab42cb8207
Create Date: 2025-10-10 10:27:05.459197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04c690da4e15'
down_revision: Union[str, None] = '07ab42cb8207'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('policy_type', sa.String(), nullable=True),
    sa.Column('context_field', sa.String(), nullable=True),
    sa.Column('natural_language_rule', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_policies_context_field'), 'ai_policies', ['context_field'], unique=False)
    op.create_index(op.f('ix_ai_policies_id'), 'ai_policies', ['id'], unique=False)
    op.create_index(op.f('ix_ai_policies_name'), 'ai_policies', ['name'], unique=False)
    op.create_index(op.f('ix_ai_policies_policy_type'), 'ai_policies', ['policy_type'], unique=False)
    op.create_table('extraction_configurations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('schema_json', sa.JSON(), nullable=True),
    sa.Column('natural_language_description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extraction_configurations_id'), 'extraction_configurations', ['id'], unique=False)
    op.create_index(op.f('ix_extraction_configurations_name'), 'extraction_configurations', ['name'], unique=True)
    op.create_table('failed_ingestions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('raw_data_payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_failed_ingestions_id'), 'failed_ingestions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_failed_ingestions_id'), table_name='failed_ingestions')
    op.drop_table('failed_ingestions')
    op.drop_index(op.f('ix_extraction_configurations_name'), table_name='extraction_configurations')
    op.drop_index(op.f('ix_extraction_configurations_id'), table_name='extraction_configurations')
    op.drop_table('extraction_configurations')
    op.drop_index(op.f('ix_ai_policies_policy_type'), table_name='ai_policies')
    op.drop_index(op.f('ix_ai_policies_name'), table_name='ai_policies')
    op.drop_index(op.f('ix_ai_policies_id'), table_name='ai_policies')
    op.drop_index(op.f('ix_ai_policies_context_field'), table_name='ai_policies')
    op.drop_table('ai_policies')
    # ### end Alembic commands ###
